### ISSUE TITLE
Not working with HA 2022.12.6

### ISSUE THREAD

**Issue by boardlord1** [tolnai/esphome-dashboard-lilygo-t5#1] opened 2022-12-15 08:14 UTC
Hi/helló,

noticed that on 2022.12.6 it's not working properly anymore... It doesn't display the forecast anymore, only the current weather: 
![image](https://user-images.githubusercontent.com/8179205/207806330-b2bef010-31c6-4949-80a9-b5502ac40016.png)

If I try to set "show_forecast:" to true in the card config, it immediately switched back to false... Newest multiscrape is used through HACS. Could you investigate? Köszi :)

**Comment by tolnai** [comment] 2022-12-15 09:17
I haven't upgraded to 2022.12 yet, but will try to do in the coming days. My thinking here would be that the multiscrape config shouldn't be impacted by HA upgrade - is it possible that multiscrape itself has an issue with the new HA version? Did you check the logs for concrete errors?

**Comment by boardlord1** [comment] 2022-12-15 10:52
This is what I got from the logs:
![image](https://user-images.githubusercontent.com/8179205/207840462-8408c186-a083-45b3-a710-ed3a864f1c75.png)

**Comment by tolnai** [comment] 2022-12-15 20:49
Looks like it is also wrong without updating HA, so perhaps the idokep site/css changed. Will update selectors later.

**Comment by tolnai** [comment] 2022-12-16 13:31
Got it, issue is caused by a special different style for days where min and max are close to each other... :D
Pushed a fix to support this scenario as well.

**Comment by boardlord1** [comment] 2022-12-16 13:54
Szuper, minden oké már :)

Thanks!!

**Comment by boardlord1** [comment] 2022-12-16 18:33
Unfortunately after a few hours it's back at showing only the current weather, no forecast...
![image](https://user-images.githubusercontent.com/8179205/208165606-c73e1400-b220-4eaa-aa70-2094c3014638.png)

**Comment by tolnai** [comment] 2022-12-16 22:04
Damn, they use a different css class for 1, 2 or more degrees difference between min and max temperature... :/ Added a commit to support that as well.

**Comment by boardlord1** [comment] 2022-12-16 22:17
Ok, seems to work again now :) Hopefully you've successfully covered all the edge cases now. Will observe for the next few days

**Closed as completed** 2023-01-04 06:03 UTC
